//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string userId { get; set; }
        public string name { get; set; }
        public string userType { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Chair Chair { get; set; }
        public virtual Reviewer Reviewer { get; set; }
    }
}
